### LOGIN
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "hoangduy12823@gmail.com",
  "password": "623844",
  "cartId": "671f9a8931903f00fc714704"
}

### REGISTER
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "name": "Nguyễn Hoàng Duy",
  "email": "copperhead87123326@mailnuo.com",
  "password": "123456",
  "cartId": "671f9a8931903f00fc714704"
}

### LOGOUT
POST http://localhost:3000/api/v1/auth/logout

### FORGOT PASSWORD
POST http://localhost:3000/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "hoangduy12823@gmail.com"
}

### RESET PASSWORD
POST http://localhost:3000/api/v1/auth/reset-password
Content-Type: application/json

{
  "email": "hoangduy12823@gmail.com",
  "password": "623844",
  "otp": "623844"
}

### GOOGLE (NOTE: Use browser to open this link)
# GET http://localhost:3000/api/v1/auth/google?cartId=671f9a8931903f00fc714704