### GET 
GET http://localhost:3000/api/v1/products

### GET BY ID
GET http://localhost:3000/api/v1/products/67184e01475b17583ddbeddc

### INSERT (ADMIN)
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
    "name": "Test Product",
    "images": [],
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc",
    "category": "home",
    "variants": [
        {
            "id": "variant_011",
            "quantity": 80,
            "importPrice": 100.0,
            "retailPrice": 149.99,
            "details": {
                "color": "Black",
                "material": "Mesh",
                "adjustable": "Yes"
            }
        },
        {
            "id": "variant_012",
            "quantity": 60,
            "importPrice": 110.0,
            "retailPrice": 169.99,
            "details": {
                "color": "Grey",
                "material": "Leather",
                "adjustable": "Yes"
            }
        }
    ],
    "brand": "ComfortSeating",
    "relevantProducts": [],
    "details": {
        "weightCapacity": "250 lbs",
        "swivel": "Yes",
        "wheels": "Yes"
    },
    "ratings": 4.3,
    "tags": ["office chair", "ergonomic", "home office", "furniture"]
}


### UPDATE (ADMIN)
PATCH http://localhost:3000/api/v1/products/67184e01475b17583ddbeddc
Content-Type: application/json

{
  "brand": "LG"
}

### UPDATE IMAGE (ADMIN)
PATCH http://localhost:3000/api/v1/products/650f1a2c9a68a234567890ab
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="default_product.png"
Content-Type: image/png

< ./images/default_product.png
--boundary--

### DELETE (ADMIN, SOFT DELETE)
DELETE http://localhost:3000/api/v1/products/67184e01475b17583ddbeddc

### DELETE PERMANENTLY (ADMIN, HARD DELETE)
DELETE http://localhost:3000/api/v1/products/67184e01475b17583ddbeddc/permanent