### GET
GET http://localhost:3000/api/v1/vouchers

### GET WITH FILTER (discountType, code, used, limit, page)
GET http://localhost:3000/api/v1/vouchers?discountType=percent&code=85&used=false

### GET WITH PAGINATION
GET http://localhost:3000/api/v1/vouchers?page=2&limit=2

### GET BY ID
GET http://localhost:3000/api/v1/vouchers/6713ac1387a3a32890090e4b

### INSERT 
POST http://localhost:3000/api/v1/vouchers
Content-Type: application/json

{
  "code": "MYCODE-C332-060A-4E4F-BF1B-9ECB",
  "discount": {
    "type": "percent",
    "value": 10
  },
  "expirationDate": "2024-10-19T19:20:00.000Z"
}

### UPDATE BY ID
PATCH http://localhost:3000/api/v1/vouchers/6713ac1387a3a32890090e4b
Content-Type: application/json

{
  "code": "C332-060A-4E4F-BF1B-9ECB"
}

### DELETE BY ID
DELETE http://localhost:3000/api/v1/vouchers/6713ac1387a3a32890090e4b

### GENERATE CODES (NOTE: -7 hours from current timestampt)
POST http://localhost:3000/api/v1/vouchers/generate-codes 
Content-Type: application/json

{
  "count": 10,
  "discount": {
    "type": "percent",
    "value": 10
  },
  "expirationDate": "2024-11-01T19:20:00.000Z"
}

### VALIDATE CODE
POST http://localhost:3000/api/v1/vouchers/code
Content-Type: application/json

{
  "code": "MYCODE-C332-060A-4E4F-BF1B-9ECB"
}