db = db.getSiblingDB("EComm");

db.products.insertMany([
    {
        _id: new ObjectId("67184af312b13e784a0570b0"),
        name: "4K Ultra HD Smart TV",
        images: [],
        description:
            "Experience immersive viewing with the latest 4K Ultra HD Smart TV. Perfect for movies, gaming, and streaming.",
        category: "electronics",
        brand: "LG",
        variants: [
            {
                id: "variant_001",
                quantity: 50,
                importPrice: 12704000,
                retailPrice: 20325000,
                details: { size: "55 inches", resolution: "4K UHD", displayType: "LED" },
            },
            {
                id: "variant_002",
                quantity: 30,
                importPrice: 15244800,
                retailPrice: 25400000,
                details: { size: "65 inches", resolution: "4K UHD", displayType: "QLED" },
            },
        ],
        relevantProducts: [],
        details: {
            connectivity: "Wi-Fi, Bluetooth",
            smartFeatures: "Voice control, App store, Streaming apps",
            refreshRate: "120Hz",
        },
        ratings: 4.6,
        tags: ["smart tv", "4K", "UHD", "electronics"],
        isDeleted: false,
        createdAt: new Date(Date.parse("2024-10-22T15:49:16.088Z")),
        updatedAt: new Date(Date.parse("2024-10-22T15:49:16.088Z")),
    },
    {
        _id: new ObjectId("6510f12d9b5a1234567890ae"),
        name: "Noise-Cancelling Headphones",
        images: [],
        description: "Immerse yourself in music with these high-quality, noise-cancelling headphones.",
        category: "electronics",
        brand: "Sony",
        variants: [
            {
                id: "variant_003",
                quantity: 100,
                importPrice: 3811200,
                retailPrice: 7622000,
                details: { color: "Black", batteryLife: "30 hours", connectivity: "Bluetooth 5.0" },
            },
            {
                id: "variant_004",
                quantity: 75,
                importPrice: 4319360,
                retailPrice: 8890000,
                details: { color: "Silver", batteryLife: "32 hours", connectivity: "Bluetooth 5.0" },
            },
        ],
        relevantProducts: [],
        details: { drivers: "40mm", noiseCancelling: "Active", warranty: "2 years" },
        ratings: 4.8,
        tags: ["headphones", "noise-cancelling", "electronics"],
        isDeleted: false,
        createdAt: new Date(Date.parse("2024-10-22T15:59:13.218Z")),
        updatedAt: new Date(Date.parse("2024-10-22T15:59:13.218Z")),
    },
    {
        _id: new ObjectId("6510f12d9b5a1234567890af"),
        name: "Smartphone 12 Pro",
        images: [],
        description: "Latest generation smartphone with ultra-fast processing and a stunning display.",
        category: "electronics",
        brand: "SmartTech",
        variants: [
            {
                id: "variant_005",
                quantity: 200,
                importPrice: 17785600,
                retailPrice: 25400000,
                details: { color: "Silver", storage: "128GB" },
            },
            {
                id: "variant_006",
                quantity: 150,
                importPrice: 19056000,
                retailPrice: 25400000,
                details: { color: "Gold", storage: "256GB" },
            },
        ],
        relevantProducts: [],
        details: { connectivity: "5G, Wi-Fi 6", battery: "4500mAh", camera: "108MP" },
        ratings: 4.7,
        tags: ["smartphone", "mobile", "5G", "fast-charging"],
        isDeleted: false,
        createdAt: new Date(Date.parse("2024-10-22T15:59:13.219Z")),
        updatedAt: new Date(Date.parse("2024-10-22T15:59:13.219Z")),
    },
    {
        _id: new ObjectId("67184af312b13e784a0570b1"),
        name: "Gaming Laptop GX500",
        images: [],
        description: "High-performance gaming laptop with powerful graphics and fast processors.",
        category: "electronics",
        brand: "GamePro",
        variants: [
            {
                id: "variant_007",
                quantity: 75,
                importPrice: 30489600,
                retailPrice: 38000000,
                details: { processor: "Intel i7", RAM: "16GB" },
            },
            {
                id: "variant_008",
                quantity: 40,
                importPrice: 35571200,
                retailPrice: 45730000,
                details: { processor: "Intel i9", RAM: "32GB" },
            },
        ],
        relevantProducts: [],
        details: { storage: "512GB SSD", graphicsCard: "NVIDIA RTX 3060", coolingSystem: "Advanced" },
        ratings: 4.5,
        tags: ["gaming", "laptop", "high-performance", "graphics"],
        isDeleted: false,
        createdAt: new Date(Date.parse("2024-10-22T15:59:13.227Z")),
        updatedAt: new Date(Date.parse("2024-10-22T15:59:13.227Z")),
    },
    {
        _id: new ObjectId("67184af312b13e784a0570b2"),
        name: "Smart Home Speaker",
        images: [],
        description: "Smart home speaker with voice assistant integration and superior sound quality.",
        category: "home",
        brand: "SmartHome",
        variants: [
            {
                id: "variant_009",
                quantity: 150,
                importPrice: 2032640,
                retailPrice: 3300000,
                details: { color: "Grey", assistantSupport: "Yes" },
            },
            {
                id: "variant_010",
                quantity: 100,
                importPrice: 2286720,
                retailPrice: 3810000,
                details: { color: "Black", assistantSupport: "Yes" },
            },
        ],
        relevantProducts: [],
        details: { connectivity: "Wi-Fi, Bluetooth", audioQuality: "High-fidelity" },
        ratings: 4.4,
        tags: ["smart home", "speaker", "voice assistant", "audio"],
        isDeleted: false,
        createdAt: new Date(Date.parse("2024-10-22T15:59:13.227Z")),
        updatedAt: new Date(Date.parse("2024-10-22T15:59:13.227Z")),
    },
    {
        _id: new ObjectId("67184af312b13e784a0570b3"),
        name: "Ergonomic Office Chair",
        images: [],
        description: "Comfortable ergonomic office chair with adjustable lumbar support and breathable mesh.",
        category: "home",
        brand: "ComfortSeating",
        variants: [
            {
                id: "variant_011",
                quantity: 80,
                importPrice: 2540800,
                retailPrice: 3810000,
                details: { color: "Black", material: "Mesh", adjustable: "Yes" },
            },
            {
                id: "variant_012",
                quantity: 60,
                importPrice: 2794880,
                retailPrice: 4310000,
                details: { color: "Grey", material: "Leather", adjustable: "Yes" },
            },
        ],
        relevantProducts: [],
        details: { weightCapacity: "250 lbs", swivel: "Yes", wheels: "Yes" },
        ratings: 4.3,
        tags: ["office chair", "ergonomic", "home office", "furniture"],
        isDeleted: false,
        createdAt: new Date(Date.parse("2024-10-22T16:07:13.509Z")),
        updatedAt: new Date(Date.parse("2024-10-22T16:07:13.509Z")),
    },
    {
        _id: new ObjectId("67184af312b13e784a0570b4"),
        name: "Yoga Mat with Carrying Strap",
        images: [],
        description: "Non-slip yoga mat with excellent grip and cushioning for all types of exercises.",
        category: "sports",
        brand: "FitGear",
        variants: [
            {
                id: "variant_013",
                quantity: 150,
                importPrice: 381120,
                retailPrice: 761000,
                details: { color: "Purple", thickness: "6mm", material: "PVC" },
            },
            {
                id: "variant_014",
                quantity: 120,
                importPrice: 431936,
                retailPrice: 889000,
                details: { color: "Blue", thickness: "8mm", material: "TPE" },
            },
        ],
        relevantProducts: [],
        details: { slipResistant: "Yes", portability: "Lightweight", careInstructions: "Hand wash" },
        ratings: 4.7,
        tags: ["yoga", "fitness", "exercise", "sports gear"],
        isDeleted: false,
        createdAt: new Date(Date.parse("2024-10-22T16:07:13.509Z")),
        updatedAt: new Date(Date.parse("2024-10-22T16:07:13.509Z")),
    },
    {
        _id: new ObjectId("67184af312b13e784a0570b5"),
        name: "Treadmill for Home Use",
        images: [],
        description: "Compact foldable treadmill perfect for home cardio workouts with digital display.",
        category: "sports",
        brand: "CardioPro",
        variants: [
            {
                id: "variant_015",
                quantity: 40,
                importPrice: 7622400,
                retailPrice: 12700000,
                details: { maxSpeed: "10 mph", incline: "Manual", foldable: "Yes" },
            },
            {
                id: "variant_016",
                quantity: 30,
                importPrice: 8892800,
                retailPrice: 15240000,
                details: { maxSpeed: "12 mph", incline: "Automatic", foldable: "Yes" },
            },
        ],
        relevantProducts: [],
        details: { weightCapacity: "300 lbs", display: "Digital", programs: "5 Pre-set Programs" },
        ratings: 4.4,
        tags: ["treadmill", "home gym", "fitness", "exercise"],
        isDeleted: false,
        createdAt: new Date(Date.parse("2024-10-22T16:07:13.510Z")),
        updatedAt: new Date(Date.parse("2024-10-22T16:07:13.510Z")),
    },
    {
        _id: new ObjectId("67184af312b13e784a0570b6"),
        name: "Wireless eBook Reader",
        images: [],
        description: "Lightweight eBook reader with adjustable brightness and a high-resolution display.",
        category: "books",
        brand: "ReadPro",
        variants: [
            {
                id: "variant_017",
                quantity: 200,
                importPrice: 1905600,
                retailPrice: 3300000,
                details: { storage: "8GB", screenSize: "6 inches", batteryLife: "4 weeks" },
            },
            {
                id: "variant_018",
                quantity: 150,
                importPrice: 2286720,
                retailPrice: 4060000,
                details: { storage: "32GB", screenSize: "7 inches", batteryLife: "6 weeks" },
            },
        ],
        relevantProducts: [],
        details: { connectivity: "Wi-Fi", formatSupport: "ePub, PDF, MOBI", waterproof: "Yes" },
        ratings: 4.6,
        tags: ["ebook", "reader", "portable", "books"],
        isDeleted: false,
        createdAt: new Date(Date.parse("2024-10-22T16:07:13.510Z")),
        updatedAt: new Date(Date.parse("2024-10-22T16:07:13.510Z")),
    },
    {
        _id: new ObjectId("67184af312b13e784a0570b7"),
        name: "Multi-Purpose Foldable Step Ladder",
        images: [],
        description: "Durable and lightweight foldable step ladder for home and outdoor use.",
        category: "others",
        brand: "EasyReach",
        variants: [
            {
                id: "variant_019",
                quantity: 100,
                importPrice: 1016320,
                retailPrice: 1778000,
                details: { steps: "3", height: "4 ft", material: "Aluminum" },
            },
            {
                id: "variant_020",
                quantity: 80,
                importPrice: 1143360,
                retailPrice: 2030000,
                details: { steps: "4", height: "5 ft", material: "Steel" },
            },
        ],
        relevantProducts: [],
        details: { weightCapacity: "250 lbs", foldable: "Yes", slipResistant: "Yes" },
        ratings: 4.5,
        tags: ["ladder", "home improvement", "tools", "outdoor"],
        isDeleted: false,
        createdAt: new Date(Date.parse("2024-10-22T16:07:13.510Z")),
        updatedAt: new Date(Date.parse("2024-10-22T16:07:13.510Z")),
    },
]);
